#!/bin/bash

# This script generates a header containing a version string for the CLVTreeScaper binary.
# The version is of the format:
#
#    <latest_release>[-<commits since release>-<current commit hash>][_dirty]
#
# Where the commit hash and dirty flag are only present when commits have been made since the
# most recent release tag, and there are any tracked, uncommitted changes in the repository, respectively.
#
# For example:
#
# version = v2.0.0-alpha.1                  # This is the first alpha release of v2.0.0.
# version = v2.0.0-alpha.1-3-12345678       # Commit 12345678 and two others have been added since the last release.
# version = v2.0.0-alpha.1-3-12345678_dirty # The same as above, but some uncommitted changes are present in tracked files.

version_string="$(git describe)$(git status --porcelain | grep -v '^?' >/dev/null && echo _dirty)"
version_file=version.hpp
version_variable=program_version

# Only regenerate if the version differs
if [[ -f $version_file ]]; then
    latest_version=$(grep $version_variable $version_file | egrep -o '"v.*"')
fi
if [[ "$latest_version" == "\"$version_string\"" ]]; then
    exit 0
fi

echo "Regenerating ${version_file}..."

echo "// Automatically generated by generate_version.sh" > $version_file
echo "#pragma once" >> $version_file
echo "#include <string>" >> $version_file
echo "static const std::string $version_variable __attribute__((used)) = \"${version_string}\";" >> $version_file

