name: CLI_Docker CI

on:
  push:
    branches: [ docker ]
  pull_request:
    branches: [ docker ]

jobs:
  build:

    runs-on: ubuntu:18.04

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make